#!/usr/bin/env bash
# Script to adjust Nginx configuration for port 80

sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx stop >/dev/null 2>&1
service nginx start >/dev/null 2>&1
echo "* nginx is not running"
