#!/usr/bin/env bash
# Script to install and configure Nginx on Ubuntu

# Update package lists and install Nginx
apt-get update -y
apt-get install nginx -y

# Verify Nginx installation and ensure it's listening on port 80
netstat -tuln | grep ':80'

# Configure Nginx to display 'Holberton School' at root
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx
service nginx restart

